### ISSUE TITLE
The specified language version is too high. The highest supported language version is 2.16

### ISSUE THREAD

**Issue by erleizh** [xuzhongpeng/git_hooks#15]
git commit 时提示 
```shell
tool/git_hooks.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.16
```

**Comment by erleizh** [comment]
``` yaml
environment:
  sdk: "2.17.0"
  flutter: "3.0.0"
```
